#adapted from example in docker documentation
version: '3'

services:
   web:
      build: .
      volumes:
         - .:/code
      expose:
         - 8000
      command: python /code/finalproject/manage.py runserver 0.0.0.0:8000

   redis:
      image: redis
      expose:
         - 6379

   nginx:
      restart: always
      build: ./nginx/
      volumes:
         - ./finalproject/finalapp/static:/static/
      depends_on:
       - web
      ports:
         - 80:80
      links:
         - web:web