# Generated by Django 3.1.1 on 2020-12-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0004_chatlogmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlogmessage',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
