# Generated by Django 3.1.1 on 2020-12-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0006_chatuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
